param(
    [string]$Distro = "Ubuntu",
    [string]$Engine,
    [string]$Model,
    [string]$ClaudePermissionMode,
    [string]$ClaudeBin,
    [string]$CodexBin,
    [int]$LoopInterval,
    [int]$CycleTimeoutSeconds,
    [int]$MaxConsecutiveErrors,
    [int]$CooldownSeconds,
    [int]$LimitWaitSeconds,
    [int]$MaxLogs,
    [switch]$AutoApproveSafe,
    [string]$SandboxMode,
    [string]$CodexSandboxMode
)

$ErrorActionPreference = "Stop"

function Assert-WslAvailable {
    if (-not (Get-Command wsl.exe -ErrorAction SilentlyContinue)) {
        throw "wsl.exe not found. Enable WSL first."
    }
}

function Get-RepoPaths {
    $repoWin = (Resolve-Path (Join-Path $PSScriptRoot "..\\..")).Path
    $repoWinForWsl = $repoWin -replace "\\", "/"
    $repoWslRaw = & wsl.exe wslpath -a "$repoWinForWsl"
    if (-not $repoWslRaw) {
        throw "Failed to convert repository path to WSL path."
    }
    $repoWsl = $repoWslRaw.Trim()
    if (-not $repoWsl) {
        throw "Failed to convert repository path to WSL path."
    }
    return @{
        RepoWin = $repoWin
        RepoWsl = $repoWsl
    }
}

function Invoke-WslCommand {
    param(
        [Parameter(Mandatory = $true)][string]$RepoWsl,
        [Parameter(Mandatory = $true)][string]$Command,
        [switch]$IgnoreExitCode
    )

    $output = & wsl.exe -d $Distro --cd $RepoWsl bash -lc $Command 2>&1
    $code = $LASTEXITCODE
    if ($output) {
        foreach ($line in $output) {
            Write-Host $line
        }
    }
    if (-not $IgnoreExitCode -and $code -ne 0) {
        throw "WSL command failed ($code): $Command"
    }
    return $code
}

function Write-AutoLoopEnv {
    param(
        [Parameter(Mandatory = $true)][string]$RepoWin,
        [string[]]$EnvLines = @()
    )

    $envFile = Join-Path $RepoWin ".auto-loop.env"
    $lines = @(
        "# Auto-generated by start-win.ps1 at $(Get-Date -Format o)",
        "# Edit manually only if you know what you are doing."
    )
    $lines += $EnvLines

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($envFile, $lines, $utf8NoBom)
    Write-Host "Wrote env file: $envFile"
}

Assert-WslAvailable
$paths = Get-RepoPaths
$repoWin = $paths.RepoWin
$repoWsl = $paths.RepoWsl

if ($PSBoundParameters.ContainsKey("Engine")) {
    $engineNormalized = $Engine.ToLowerInvariant()
    if ($engineNormalized -notin @("claude", "codex", "gemini")) {
        throw "Unsupported Engine '$Engine'. Use 'claude', 'codex', or 'gemini'."
    }
    $Engine = $engineNormalized
}

if ($PSBoundParameters.ContainsKey("CycleTimeoutSeconds") -and $CycleTimeoutSeconds -lt 300) {
    Write-Warning "CycleTimeoutSeconds=$CycleTimeoutSeconds is very low for real cycles and may cause frequent timeouts. Recommended: 900-1800."
}

$envLines = @()
if ($PSBoundParameters.ContainsKey("Engine")) { $envLines += "ENGINE=$Engine" }
if ($PSBoundParameters.ContainsKey("Model")) { $envLines += "MODEL=$Model" }
if ($PSBoundParameters.ContainsKey("ClaudePermissionMode")) { $envLines += "CLAUDE_PERMISSION_MODE=$ClaudePermissionMode" }
if ($PSBoundParameters.ContainsKey("ClaudeBin")) { $envLines += "CLAUDE_BIN=$ClaudeBin" }
if ($PSBoundParameters.ContainsKey("CodexBin")) { $envLines += "CODEX_BIN=$CodexBin" }
if ($PSBoundParameters.ContainsKey("LoopInterval")) { $envLines += "LOOP_INTERVAL=$LoopInterval" }
if ($PSBoundParameters.ContainsKey("CycleTimeoutSeconds")) { $envLines += "CYCLE_TIMEOUT_SECONDS=$CycleTimeoutSeconds" }
if ($PSBoundParameters.ContainsKey("MaxConsecutiveErrors")) { $envLines += "MAX_CONSECUTIVE_ERRORS=$MaxConsecutiveErrors" }
if ($PSBoundParameters.ContainsKey("CooldownSeconds")) { $envLines += "COOLDOWN_SECONDS=$CooldownSeconds" }
if ($PSBoundParameters.ContainsKey("LimitWaitSeconds")) { $envLines += "LIMIT_WAIT_SECONDS=$LimitWaitSeconds" }
if ($PSBoundParameters.ContainsKey("MaxLogs")) { $envLines += "MAX_LOGS=$MaxLogs" }
if ($AutoApproveSafe) { $envLines += "AUTO_APPROVE_SAFE=1" }
if ($PSBoundParameters.ContainsKey("SandboxMode")) {
    $envLines += "CODEX_SANDBOX_MODE=$SandboxMode"
} elseif ($PSBoundParameters.ContainsKey("CodexSandboxMode")) {
    $envLines += "CODEX_SANDBOX_MODE=$CodexSandboxMode"
}

Write-AutoLoopEnv -RepoWin $repoWin -EnvLines $envLines

$null = Invoke-WslCommand -RepoWsl $repoWsl -Command "command -v systemctl >/dev/null 2>&1 && systemctl --user --version >/dev/null 2>&1"

$installedCode = Invoke-WslCommand -RepoWsl $repoWsl -Command "systemctl --user cat auto-company.service >/dev/null 2>&1" -IgnoreExitCode
if ($installedCode -ne 0) {
    Write-Host "auto-company.service not installed; running make install..."
    $null = Invoke-WslCommand -RepoWsl $repoWsl -Command "make install"
}

$null = Invoke-WslCommand -RepoWsl $repoWsl -Command "systemctl --user start auto-company.service"
Write-Host "WSL daemon started: auto-company.service"

$awakeScript = Join-Path $repoWin "scripts\\windows\\awake-guardian-win.ps1"
if (-not (Test-Path $awakeScript)) {
    throw "Missing awake guardian script: $awakeScript"
}

& $awakeScript -Action start
if ($LASTEXITCODE -ne 0) {
    Write-Error "Daemon started, but awake guardian failed to start. System sleep is not protected."
    exit 2
}

$anchorScript = Join-Path $repoWin "scripts\\windows\\wsl-anchor-win.ps1"
if (-not (Test-Path $anchorScript)) {
    throw "Missing WSL anchor script: $anchorScript"
}

& $anchorScript -Action start -Distro $Distro -RepoWsl $repoWsl
if ($LASTEXITCODE -ne 0) {
    Write-Error "Daemon started, but WSL anchor failed to start. Background persistence may be unstable."
    exit 3
}

Write-Host ""
Write-Host "Use .\scripts\windows\status-win.ps1 to inspect daemon and loop status."
exit 0
